# Generated by Django 5.1 on 2024-09-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificaterequest',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='certificaterequest',
            old_name='reason',
            new_name='request_purpose',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='certificaterequest',
            name='student_id',
        ),
        migrations.AddField(
            model_name='certificaterequest',
            name='lrn',
            field=models.CharField(default=123456789012, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='certificate_type',
            field=models.CharField(choices=[('Certification', 'Certification'), ('Form 137', 'Form 137'), ('Form 138', 'Form 138'), ('Good_Moral', 'Good Moral Certificate')], max_length=50),
        ),
    ]
